- hosts: webservers
  become: true
  become_user: root
  vars:
    item:
      - git 
      - docker
  tasks:
    - name: install git an docker
      yum:
        name: "{{item}}"
        state: present
    - name: start docker service
      service:
        name: docker
        state: started
    - name: clone the repo
      git:
        repo: https://github.com/rohitcheta/DECProject.git
        dest: /tmp/myrepo
    - name: Build the image from dockerfile
      command: chdir=/tmp/myrepo docker build -t decimage .
    - name: Deploy the image
      command: docker run -d -P decimage 
