- hosts: webservers
  become: true
  become_user: root
  vars:
    item:
      - git 
      - docker
  tasks:
    - name: install git an docker
      yum:
        name: "{{item}}"
        state: present
    - name: start docker service
      service:
        name: docker
        state: started

